name: Build AN actors (codes + rôles)

on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/build_an_actors.mjs'
      - 'data/an16/json/**'
      - '.github/workflows/build-an-actors.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Préparer les dossiers
        run: mkdir -p data

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Générer data/an_actors.json (fusion acteurs + organes)
        run: node scripts/build_an_actors.mjs

      - name: Commit & push si modifié
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/an_actors.json
          git diff --quiet && git diff --staged --quiet || git commit -m "build(an): update an_actors.json"
          git push
