name: Update deputes.json (daily)

# Déclenchement automatique et manuel
on:
  workflow_dispatch:   # permet de lancer à la main
  schedule:
    - cron: "17 3 * * *"  # tous les jours à 03:17 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Télécharger ton dépôt
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Installer l’outil jq (sert à filtrer le JSON)
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # 3. Télécharger les données de l’Assemblée nationale (500 députés max)
      - name: Fetch ODS dataset (500 rows)
        run: |
          curl -sS "https://data.assemblee-nationale.fr/api/records/1.0/search/?dataset=deputes-en-exercice&rows=500" -o /tmp/ods.json

      # 4. Transformer les données en un fichier simplifié deputes.json
      - name: Build deputes.json
        run: |
          mkdir -p deputes
          jq '
            .records
            | map({
                id: (.recordid // ""),
                nom: (
                  ((.fields.prenom_usuel // .fields.prenom // "") + " " + (.fields.nom_civil // .fields.nom // .fields.nom_de_famille // .fields.nom_usuel // "")) 
                  | gsub("^\\s+|\\s+$";"")
                ),
                circo: (.fields.lib_circo // ""),
                dept:  (.fields.lib_dept  // .fields.departement // ""),
                groupe:(.fields.groupe_sigle // .fields.groupe // .fields.groupe_libelle // ""),
                email: (.fields.mail // .fields.email // "")
              })
          ' /tmp/ods.json > deputes/deputes.json

      # 5. Enregistrer automatiquement le fichier dans ton dépôt
      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update deputes.json from ODS"
          file_pattern: deputes/deputes.json
