name: Update deputes.json (daily)

on:
  workflow_dispatch:   # permet de lancer manuellement
  schedule:
    - cron: "0 3 * * *"   # tous les jours à 3h du matin UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Télécharger et dézipper les données AN
        run: |
          mkdir -p data
          curl -L -o data/am010.zip https://data.assemblee-nationale.fr/static/openData/repository/AMO/deputes/AMO10_deputes_actifs_mandats_actifs_organes.json.zip
          unzip -o data/am010.zip -d data/

      - name: Fusionner acteurs et mandats en deputes.json
        run: |
          mkdir -p deputes
          node <<'EOF'
          const fs = require('fs');
          const acteurs = fs.readdirSync('data/json/acteur').map(f => JSON.parse(fs.readFileSync('data/json/acteur/' + f)));
          const mandats = fs.readdirSync('data/json/deport').map(f => JSON.parse(fs.readFileSync('data/json/deport/' + f)));
          const organes = fs.readdirSync('data/json/organe').map(f => JSON.parse(fs.readFileSync('data/json/organe/' + f)));

          // Index organes par uid
          const orgMap = {};
          organes.forEach(o => orgMap[o.uid] = o);

          const res = [];
          for (const a of acteurs) {
            const m = (a.mandats || []).find(m => m.actif === true);
            if (!m) continue;
            const o = orgMap[m.organeRef] || {};
            res.push({
              id: a.uid,
              nom: `${a.nom} ${a.prenom}`,
              circo: m.circonscription,
              dept: m.departement,
              groupe: o.libelleAbrev || "",
              email: a.email
            });
          }

          fs.writeFileSync('deputes/deputes.json', JSON.stringify(res, null, 2));
          EOF

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add deputes/deputes.json
          git commit -m "Mise à jour deputes.json"
          git push
