name: Update deputes.json (daily, AMO10 L17)

on:
  workflow_dispatch:            # lancement manuel
  schedule:
    - cron: "17 3 * * *"        # tous les jours à 03:17 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install unzip + jq
        run: sudo apt-get update && sudo apt-get install -y unzip jq

      - name: Download AMO10 (L17) ZIP
        run: |
          set -eux
          curl -fsSL \
            "https://data.assemblee-nationale.fr/static/openData/repository/17/amo/deputes_actifs_mandats_actifs_organes/AMO10_deputes_actifs_mandats_actifs_organes.json.zip" \
            -o data.zip

      - name: Extract JSON files
        run: |
          set -eux
          rm -rf data
          mkdir -p data
          unzip -o data.zip -d data
          echo "Aperçu des fichiers extraits :"
          find data -maxdepth 3 -type f | head -n 50

      # --- Mapping auto des groupes à partir des ORGANES (GP) ---
      - name: Build groupes.json (codes PO -> sigle/libellé)
        run: |
          set -eux
          mkdir -p deputes
          jq -s '
            map(.organe)                                   |
            map(select(.codeType == "GP"))                 |
            map({
              code:    (.uid?["#text"] // .uid // ""),
              sigle:   (.libelleAbrege // .acronyme // .libelle // ""),
              libelle: (.libelle // .libelleAbrege // .acronyme // "")
            })                                             |
            map(select(.code != ""))                       |
            unique_by(.code)
          ' data/json/organe/*.json > deputes/groupes.json

          jq 'length' deputes/groupes.json

      # --- Liste simplifiée des députés à partir des ACTEURS ---
      - name: Build deputes.json (parser AMO10)
        run: |
          set -eux
          mkdir -p deputes
          jq -s '
            map(
              .acteur
              | ( [ ((.adresses?.adresse? // [])
                      | map(select(.typeLibelle=="Mèl") | .valElec)
                    )[] ] ) as $mails
              | {
                  id:     (.uid?["#text"] // .uid // .identifiant // ""),
                  nom:    (
                           ((.etatCivil.ident?.prenom // .etatCivil?.prenom // "")
                            + " " +
                            (.etatCivil.ident?.nom    // .etatCivil?.nom    // ""))
                           | gsub("^\\s+|\\s+$";"")
                          ),
                  email:  (
                           ( $mails[] | select(test("assemblee-nationale\\.fr$")) )
                           // ($mails[0] // .mails?[0] // .email // "")
                          ),
                  _mandats: (.mandats?.mandat // [])
                }
              | .circo  = ( ._mandats | map(select(.typeOrgane=="ASSEMBLEE")) | .[0]?.election?.lieu?.numCirco    // "" )
              | .dept   = ( ._mandats | map(select(.typeOrgane=="ASSEMBLEE")) | .[0]?.election?.lieu?.departement // "" )
              | .groupe = ( ._mandats | map(select(.typeOrgane=="GP"))        | .[0]?.organes?.organeRef           // "" )
              | del(._mandats)
            )
          ' data/json/acteur/*.json > deputes/deputes.json

          jq 'length' deputes/deputes.json

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update deputes/ (groupes.json + deputes.json) from AMO10 L17"
          file_pattern: |
            deputes/groupes.json
            deputes/deputes.json
