name: Update deputes.json (daily, AMO10 L17)

on:
  workflow_dispatch:   # Permet de lancer à la main
  schedule:
    - cron: "0 2 * * *"   # Tous les jours à 2h du matin (UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install unzip + jq
        run: sudo apt-get update && sudo apt-get install -y unzip jq

      - name: Download AMO10 (L17) ZIP
        run: curl -L "https://data.assemblee-nationale.fr/static/openData/repository/17/amo/deputes_actifs_mandats_actifs_organes/AMO10_deputes_actifs_mandats_actifs_organes.json.zip" -o data.zip

      - name: Extract JSON files
        run: unzip -o data.zip -d data

      - name: Build deputes.json (simplifié)
        run: |
          mkdir -p deputes
          jq -s '
            map(.acteurs? // []) | add |
            map({
              id: (.uid // .id // .identifiant // ""),
              nom: ((.etatCivil?.prenom // "") + " " + (.etatCivil?.nom // "")),
              circo: (.mandats? | map(select(.dateFin == null)) | .[0].libelleCirco // ""),
              dept: (.mandats? | map(select(.dateFin == null)) | .[0].libelleDepartement // ""),
              groupe: (.mandats? | map(select(.dateFin == null)) | .[0].organes?[0]?.libelleAbrege // ""),
              email: (.adresses?.emails?[0]?.email // "")
            })
          ' data/json/acteur/*.json > deputes/deputes.json

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update deputes.json from AMO10"
          file_pattern: deputes/deputes.json
