name: Update sénateurs (API Sénat)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"   # chaque jour à 06:00 UTC

permissions:
  contents: write

jobs:
  update-senateur:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download senators JSON from senat.fr
        run: |
          set -euo pipefail
          mkdir -p senateur
          curl -fSL "https://www.senat.fr/api-senat/senateurs.json" \
            -o senateur/senateur_raw.json
          test -s senateur/senateur_raw.json

      - name: Commit & push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add senateur/senateur_raw.json
          git commit -m "chore(senat): update senateur_raw.json (api-senat)" || exit 0
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}
