      - name: Build lois/lois.json (simplifié depuis dossierParlementaire)
        run: |
          set -eux
          mkdir -p lois

          FILES="data_lois/dossierParlementaire/*.json"

          jq -s '
            def normdate($s):
              # $s comme "1987-05-25T00:00:00.000+02:00" -> "1987-05-25"
              if ($s // "") == "" then ""
              else ($s | sub("T.*$"; ""))
              end;

            def all_acts:
              .. | objects
              | select(has("codeActe") and has("libelleActe"));

            [
              .[] | .dossierParlementaire
              | {
                  id:    (.uid // ""),
                  titre: (.titreDossier.titre // ""),
                  type:  (.procedureParlementaire.libelle // ""),
                  # auteur : on tente d’abord un organe initiateur, sinon acteur
                  auteur: (
                    .initiateur.organes?.organe?.organeRef?.uid
                    // .initiateur.acteurs?.acteur?.acteurRef
                    // ""
                  ),
                  # url : on prend ce qu’on a ; à défaut on retient la piste Sénat si fournie
                  url: (
                    .lienDossier // .url // .titreDossier.senatChemin // ""
                  ),
                  nor:   (.nor // "")
                }
              # on cherche l’acte le plus récent pour date & état
              as $base
              | (
                  [ all_acts
                    | { d: (.dateActe // ""), 
                        etat: (.libelleActe.libelleCourt // .libelleActe.nomCanonique // "") }
                  ]
                  # on trie par date (chaîne ISO), les vides partent en bas,
                  # puis on prend le dernier (max)
                  | sort_by(.d) 
                  | last? 
                ) as $last
              | {
                  id: $base.id,
                  titre: $base.titre,
                  type: $base.type,
                  auteur: $base.auteur,
                  url: $base.url,
                  nor: $base.nor,
                  date: ( $last.d | normdate(.) ),
                  etat: ( $last.etat // "" )
                }
            ]
            # on garde ceux avec un titre non vide, on dédoublonne et on trie par date desc
            | map(select((.titre // "") != ""))
            | unique_by(.id, .titre)
            | sort_by(.date) | reverse
          ' $FILES > lois/lois.json

          echo "Total dossiers: $(jq 'length' lois/lois.json)"
